export enum CapUISpotIcon {
  PENCIL_SOFTWARE = 'PENCIL_SOFTWARE',
  EMAIL_TIMEOUT = 'EMAIL_TIMEOUT',
  EMAIL_SEND = 'EMAIL_SEND',
  RATING_CLICK = 'RATING_CLICK',
  DELETE = 'DELETE',
  USER_DISCUSS = 'USER_DISCUSS',
  BULB_SKETCH = 'BULB_SKETCH',
  UPLOAD = 'UPLOAD',
  PAPER_PLANE = 'PAPER_PLANE',
  PAPER_PLANE_1 = 'PAPER_PLANE_1',
  PAPER_PLANE_2 = 'PAPER_PLANE_2',
  ERROR = 'ERROR',
  QUESTIONNAIRE = 'QUESTIONNAIRE',
  FORM = 'FORM',
  NEWSPAPER = 'NEWSPAPER',
  REWARD = 'REWARD',
  BUBBLE = 'BUBBLE',
  SMS = 'SMS',
  PIE_CHART = 'PIE_CHART',
  CALENDAR = 'CALENDAR',
  PROJECT = 'PROJECT',
  SHEET = 'SHEET',
  ADD_CONTACT = 'ADD_CONTACT',
  MAIL = 'MAIL',
  CODES = 'CODES',
  MAP = 'MAP',
  PROHIBITED = 'PROHIBITED',
  ANALYSIS = 'ANALYSIS',
  RESULT = 'RESULT',
  CONSULTATION = 'CONSULTATION',
  VIGNETTE = 'VIGNETTE',
  CARTE = 'CARTE',
  TABLEAU = 'TABLEAU',
  SHEET_FULL = 'SHEET_FULL',
  PERMANENTLY_DELETE = 'PERMANENTLY_DELETE',
  ANONYMIZE = 'ANONYMIZE',
}

export enum CapUISpotIconSize {
  Sm = 'sm', // 56px
  Md = 'md', // 64px
  Lg = 'lg', // 124px
}
