export enum CapUISpotIcon {
  PENCIL_SOFTWARE = 'PENCIL_SOFTWARE',
  EMAIL_TIMEOUT = 'EMAIL_TIMEOUT',
  EMAIL_SEND = 'EMAIL_SEND',
  RATING_CLICK = 'RATING_CLICK',
  DELETE = 'DELETE',
  USER_DISCUSS = 'USER_DISCUSS',
  BULB_SKETCH = 'BULB_SKETCH',
  UPLOAD = 'UPLOAD',
  PAPER_PLANE_1 = 'PAPER_PLANE_1',
  PAPER_PLANE_2 = 'PAPER_PLANE_2',
  ERROR = 'ERROR',
  QUESTIONNAIRE = 'QUESTIONNAIRE',
  FORM = 'FORM',
  NEWSPAPER = 'NEWSPAPER',
  REWARD = 'REWARD',
  BUBBLE = 'BUBBLE',
  SMS = 'SMS',
  PIE_CHART = 'PIE_CHART',
  CALENDAR = 'CALENDAR',
  PROJECT = 'PROJECT',
  SHEET = 'SHEET',
}

export enum CapUISpotIconSize {
  Sm = 'sm', // 56px
  Md = 'md', // 64px
  Lg = 'lg', // 124px
}
