name: 'Chromatic'

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Chromatic needs the full git history in order to track changes over time.
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --ignore-scripts
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true
